# Generated by Django 2.2.14 on 2020-07-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_auto_20200727_2029"),
        ("quantified_flu", "0003_remove_account_public_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="report_setup",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="reports.ReportSetup",
            ),
        )
    ]
